title: Article
preset: page
pages: false
options: 
  changeTemplate: 
    - elementmenu
    - list
fields:
  text:
    label: Texte
    type: markdown
    size: medium
  notes: 
    label: Notes
    type: structure
    fields: 
      note: 
        label: note
        type: markdown
  related: 
    label: Pages liés 
    type: pages
    query: site.children.listed

